### ISSUE TITLE
Implement key nesting

### ISSUE THREAD

**Issue by wout** [wout/rosetta#1]
Allow re-use of existing translations with nested keys. For example:

```yaml
en:
  example:
    hello: "Hello %r{example.subject}!"
    subject: "world"
```

Those values will be pre-filled by the parser, so any interpolation keys in the nested keys will be transferred automatically.
