### ISSUE TITLE
Add variants

### ISSUE THREAD

**Issue by wout** [wout/rosetta#3]
Allow keys with multiple variants, for example:

```yaml
en:
  colors:
    variants:
      pink: "pink"
      teal: "teal"
      yellow: "yellow"
```

If a key has one child and it's called `variants`, then this is a multi-variant translation.
